Sprint1/apuri/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('Login/', views.Login ),
    path('Refoto/', views.Refoto, name='Refoto'),
    path('Recuperacion/', views.Recuperacion),
    path('Re_contraseña/',views.Re_contraseña),
    path('', views.Portal, name='Portal'),
    path('editar/', views.foro.crear_foro, name='editar'),
    path('Foro/', views.foro.mostrar_foros, name='foro'),
    path('crear_anuncio/', views.anun.crear_anuncios, name='anuncios'),
    path('Cambiarperfil/', views.perfil.Cambiarperfil, name='nusuario'),
    path('Login/crear_anuncio.html/', views.anun.crear_anuncios, name='anuncios'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Sprint1/apuri/models.py
from django.db import models
from django.utils import timezone
import pickle
    
# Create your models here.
class temas (models.Model):
    nombre_tema = models.CharField(max_length=200,verbose_name="Tema")

    def __str__(self):
        return self.nombre_tema


class Organizaciones(models.Model):
    nombre_organizacion = models.CharField(max_length=30, null=False, verbose_name="Nombre")
    pag_web = models.CharField(max_length=100, blank=True, null=True, verbose_name="Página Web")
    especial = models.CharField(max_length=100, blank=True, null=True, verbose_name="Especialidad")
    descripcion_organizacion= models.TextField(blank=True, null=True, verbose_name="descrpción")
    logo = models.ImageField(upload_to="Logos", null=True, verbose_name="Logo fundación")
    calendario = models.TextField(blank=True,null=True,verbose_name="Calendario google")

    def __str__ (self):

       return self.nombre_organizacion

opciones = [("Usuario","Usuario"),("Administrador","Administrador")]
a = 0

class Miembro(models.Model):
    nombre = models.CharField(max_length=30)
    apellido_pat = models.CharField(max_length=20, null=True, verbose_name="Apellido paterno")
    apellido_mat = models.CharField(max_length=20, null=True, verbose_name="Apellido materno")
    email = models.EmailField()
    contraseña = models.CharField(max_length=20, null=True, verbose_name="Contraseña(mín 8)")
    rol = models.CharField(max_length=40, null=False, default='Usuario', choices=opciones, verbose_name="Rol")
    cel = models.CharField(max_length=15, blank=True, null=True, verbose_name="Celular")
    institucion = models.ForeignKey(Organizaciones, null=True, on_delete=models.CASCADE, verbose_name="Institución")
    cargo = models.CharField(max_length=30, verbose_name="Cargo", blank=True, null=True)
    photo = models.ImageField(upload_to="perfil", blank=True, null=True, verbose_name="Foto de perfil")
    pin = models.IntegerField(default=000)

    def __str__(self):
        return self.email

class Post(models.Model):
    autor = models.ForeignKey(Miembro, on_delete=models.CASCADE)
    titulo = models.CharField(max_length=200)
    tema = models.ForeignKey(temas, on_delete=models.CASCADE, null=True)
    texto = models.TextField()
    created_date = models.DateTimeField(
            default=timezone.now)
    published_date = models.DateTimeField(
            blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.titulo

class Anuncio(models.Model):
    autor = models.ForeignKey(Miembro, on_delete=models.CASCADE, verbose_name="Autor")
    organ = models.ForeignKey(Organizaciones, on_delete=models.CASCADE, verbose_name="Organización", blank=True, null=True)
    titulo = models.CharField(max_length=200, blank=True, null=True, verbose_name="Título")
    desc = models.TextField(verbose_name="Descripción anuncio")
    tipo = models.CharField(max_length=200, verbose_name="Tipo anuncio",null=True)
    texto = models.TextField(blank=True, null=True)
    foto = models.ImageField(upload_to="Anuncios",blank=True, null=True, verbose_name="Foto de Anuncio")
    hini = models.DateTimeField(blank=True, null=True, verbose_name="Inicio evento dd/mm/aa hh:mm:ss ")
    hfin = models.DateTimeField(blank=True, null=True, verbose_name="Termino evento dd/mm/aa hh:mm:ss ")

    def __str__(self):
        return self.desc

    def save(self, *args, **kwargs):
        if not self.organ:
            self.organ = None
        super(Anuncio, self).save(*args, **kwargs)

Sprint1/templates/Foro.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Foro Colunga</title>
    <meta charset="utf-8">
    <!--  This file has been downloaded from bootdey.com @bootdey on twitter -->
    <!--  All snippets are MIT license http://bootdey.com/license -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" rel="stylesheet">
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.bundle.min.js"></script>
</head>
<center><h1>Foro colunga</h1></center>
<body>
    
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0-2/css/all.min.css" integrity="sha256-46r060N2LrChLLb5zowXQ72/iKKNiw/lAmygmHExk/o=" crossorigin="anonymous" />
<div class="container">
<div class="main-body p-0">
    <div class="inner-wrapper">
        <!-- Inner sidebar -->
        <div class="inner-sidebar">
            <!-- Inner sidebar header -->
            <div class="inner-sidebar-header justify-content-center">
                <button class="btn btn-primary has-icon btn-block" type="button" data-toggle="modal" data-target="#threadModal">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-plus mr-2">
                        <line x1="12" y1="5" x2="12" y2="19"></line>
                        <line x1="5" y1="12" x2="19" y2="12"></line>
                    </svg>
                    <a href="{% url 'editar' %}"></a>
                    
                </button>
            </div>
            <!-- /Inner sidebar header -->
            
            <!-- Inner sidebar body -->
            <div class="inner-sidebar-body p-0">
                <div class="p-3 h-100" data-simplebar="init">
                    <div class="simplebar-wrapper" style="margin: -16px;">
                        <div class="simplebar-height-auto-observer-wrapper"><div class="simplebar-height-auto-observer"></div></div>
                        <div class="simplebar-mask">
                            <div class="simplebar-offset" style="right: 0px; bottom: 0px;">
                                <div class="simplebar-content-wrapper" style="height: 100%; overflow: hidden scroll;">
                                    <div class="simplebar-content" style="padding: 16px;">
                                        <nav class="nav nav-pills nav-gap-y-1 flex-column">
                                        {% if farm %}
                                            {% for owo in farm %}   
                                                <a href="javascript:void(0)" class="nav-link nav-link-faded has-icon">{{owo.nombre_tema}} </a>
                                            {% endfor %}
                                        {% endif %}
                                        </nav>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="simplebar-placeholder" style="width: 234px; height: 292px;"></div>
                    </div>
                    <div class="simplebar-track simplebar-horizontal" style="visibility: hidden;"><div class="simplebar-scrollbar" style="width: 0px; display: none;"></div></div>
                    <div class="simplebar-track simplebar-vertical" style="visibility: visible;"><div class="simplebar-scrollbar" style="height: 151px; display: block; transform: translate3d(0px, 0px, 0px);"></div></div>
                </div>
            </div>
            <!-- /Inner sidebar body -->
        </div>
        <!-- /Inner sidebar -->

        <!-- Inner main -->
        <div class="inner-main">
            <!-- Inner main header -->
            <div class="inner-main-header">
                <a class="nav-link nav-icon rounded-circle nav-link-faded mr-3 d-md-none" href="#" data-toggle="inner-sidebar"><i class="material-icons">arrow_forward_ios</i></a>
                
                <span class="input-icon input-icon-sm ml-auto w-auto">
                    <form action="/buscador/" method="GET">
                        {% csrf_token %}

                            <input name = "q" type="text" class="form-control form-control-sm bg-gray-200 border-gray-200 shadow-none mb-4 mt-4" placeholder="Buscar Foro" />
                            
                        </form>
                </span>
            </div>
            <!-- /Inner main header -->

            <!-- Inner main body -->

            <!-- Forum List -->

             <!-- ACA VA EL MENSAJE QUE TIRA AL CREAR EL FORO  -->
             
            
                  
                {% if form %}
                    {% for iwi in form%}
                        <tbody>
                            <table class="table">
                                <div class="inner-main-body p-2 p-sm-3 collapse forum-content show">
                                    <thead class="thead-dark">
                                        <tr>
                                            <div class="card mb-2">
                                                <div class="card-body p-2 p-sm-3">
                                                    <div class="media forum-item">
                                                        <a data-toggle="collapse" data-target=".forum-content"></a>
                                                        <div class="media-body">
                                                            <h6><a data-toggle="collapse" data-target=".forum-content" class="text-body">{{iwi.titulo}}</a></h6>
                                                            <p class="text-secondary">
                                                                {{iwi.texto}}
                                                            </p>
                                                            <p class="text-muted"><a href="javascript:void({{iwi.tema}})">{{iwi.autor}}</a> {{iwi.created_date}}     tema:{{iwi.tema}}<span class="text-secondary font-weight-bold"></span></p>
                                                        </div>
                                                        <div class="text-muted small text-center align-self-center">
                                                            <span class="d-none d-sm-inline-block"><i class="far fa-eye"></i></span>
                                                            <span><i class="far fa-comment ml-2"></i> 3</span>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </tr>
                                    </thead>
                                </tbody>
                        {% endfor %}
                {% else %}
                        
                {% endif %}
                
                  
                   
            
                
            </table>
            <ul class="pagination pagination-sm pagination-circle justify-content-center mb-0">
                <li class="page-item disabled">
                    <span class="page-link has-icon"><i class="material-icons"><-</i></span>
                </li>
                <li class="page-item active"><a class="page-link" href="javascript:void(0)">1</a></li>
                <li class="page-item">
                    <a class="page-link has-icon" href="javascript:void(0)"><i class="material-icons">-></i></a>
                </li>
            </ul>
   
            <!-- /Forum List -->


            <!-- /Inner main body -->
        </div>
        <!-- /Inner main -->
    </div>

    <!-- New Thread Modal -->
    <div class="modal fade" id="threadModal" tabindex="-1" role="dialog" aria-labelledby="threadModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <form>
                    <!-- ACA VA EL FORO QUE TIENES QUE PROBAR CON TU CODIGO -->
                    <form method="POST" class="post-form">
                    <iframe src="{% url 'editar' %}" style="border-width:0" width="800" height="600" ></iframe>
                </form>
            </div>
        </div>
    </div>
</div>
</div>


<style type="text/css">
body{
    margin-top:20px;
    color: #1a202c;
    text-align: left;
    background-color: #e2e8f0;    
}
.inner-wrapper {
    position: relative;
    height: calc(100vh - 3.5rem);
    transition: transform 0.3s;
}
@media (min-width: 992px) {
    .sticky-navbar .inner-wrapper {
        height: calc(100vh - 3.5rem - 48px);
    }
}

.inner-main,
.inner-sidebar {
    position: absolute;
    top: 0;
    bottom: 0;
    display: flex;
    flex-direction: column;
}
.inner-sidebar {
    left: 0;
    width: 235px;
    border-right: 1px solid #cbd5e0;
    background-color: #fff;
    z-index: 1;
}
.inner-main {
    right: 0;
    left: 235px;
}
.inner-main-footer,
.inner-main-header,
.inner-sidebar-footer,
.inner-sidebar-header {
    height: 3.5rem;
    border-bottom: 1px solid #cbd5e0;
    display: flex;
    align-items: center;
    padding: 0 1rem;
    flex-shrink: 0;
}
.inner-main-body,
.inner-sidebar-body {
    padding: 1rem;
    overflow-y: auto;
    position: relative;
    flex: 1 1 auto;
}
.inner-main-body .sticky-top,
.inner-sidebar-body .sticky-top {
    z-index: 999;
}
.inner-main-footer,
.inner-main-header {
    background-color: #fff;
}
.inner-main-footer,
.inner-sidebar-footer {
    border-top: 1px solid #cbd5e0;
    border-bottom: 0;
    height: auto;
    min-height: 3.5rem;
}
@media (max-width: 767.98px) {
    .inner-sidebar {
        left: -235px;
    }
    .inner-main {
        left: 0;
    }
    .inner-expand .main-body {
        overflow: hidden;
    }
    .inner-expand .inner-wrapper {
        transform: translate3d(235px, 0, 0);
    }
}

.nav .show>.nav-link.nav-link-faded, .nav-link.nav-link-faded.active, .nav-link.nav-link-faded:active, .nav-pills .nav-link.nav-link-faded.active, .navbar-nav .show>.nav-link.nav-link-faded {
    color: #00963a;
    background-color: #c9d8f0;
}

.nav-pills .nav-link.active, .nav-pills .show>.nav-link {
    color: #fff;
    background-color: #00963a;
}
.nav-link.has-icon {
    display: flex;
    align-items: center;
}
.nav-link.active {
    color: #00963a;
}
.nav-pills .nav-link {
    border-radius: .25rem;
}
.nav-link {
    color: #4a5568;
}
.card {
    box-shadow: 0 1px 3px 0 rgba(0,0,0,.1), 0 1px 2px 0 rgba(0,0,0,.06);
}

.card {
    position: relative;
    display: flex;
    flex-direction: column;
    min-width: 0;
    word-wrap: break-word;
    background-color: #fff;
    background-clip: border-box;
    border: 0 solid rgba(0,0,0,.125);
    border-radius: .25rem;
}

.card-body {
    flex: 1 1 auto;
    min-height: 1px;
    padding: 1rem;
}
</style>

<script type="text/javascript">

</script>
</body>
</html>

Sprint1/templates/ReFoto.html
<!DOCTYPE HTML>
<!--
	info plantilla:
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->

{% load static %}


<html>
	<head>
		<title>Cambio perfil</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">
		<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8" crossorigin="anonymous"></script>
        <script src="https://kit.fontawesome.com/626dd6f811.js" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="{% static 'css/main2.css' %}" />
		<noscript><link rel="stylesheet" href="{% static 'css/noscript2.css' %}" /></noscript>
		<link rel="shortcut icon" type="image/x-icon" href="{% static 'css/images/logo1.ico' %}">

	</head>
	<body class="is-preload">

		<!-- Wrapper -->
			<div id="wrapper">

				<!-- Header -->
					<header id="header" class="alt">

                     <form action="/ReRefoto/" method="post">{% csrf_token %}
                    <div class="form-floating mb-3">
								<input type="email" name="usuario" class="form-control" id="floatingInput" placeholder="nombre@organización.cl">
								<label for="floatingInput">Correo electrónico</label>

							</div>

                                                  <div class="form-floating">

							            	<input type="password" name="pass" class="form-control" id="floatingPassword" placeholder=" " minlength="8">
							            	<label for="floatingPassword">Contraseña</label>

							            </div>
                        <input type="file" name="foto" accept="image/*" id="id_logo" >

                            <input type="submit" class="button wide primary" value="Guardar Foto">
                        </form>
                    </header>
            </div>
    	<script src="{% static 'js/jquery.min2.js' %}"></script>
			<script src="{% static 'js/jquery.scrollex.min2.js' %}"></script>
			<script src=  "{% static 'js/jquery.scrolly.min2.js' %}"></script>
			<script src="{% static 'js/browser.min.js2' %}"></script>
			<script src= "{% static 'js/breakpoints.min2.js' %}"></script>
			<script src="{% static 'js/util2.js' %}"></script>
			<script src="{% static 'js/main2.js' %}"></script>
    </body>
</html>

Sprint1/templates/base.html
{% load static %}
<html>
    <head>
        <title>Foro colunga</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
        <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="{% static 'css/blog.css' %}">
    </head>
    <body>
        <div class="page-header">
            <a href="{% url 'editar' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
            <h1><a href="/">COLUNGA</a></h1>
        </div>
        <div class="content container">
            <div class="row">
                <div class="col-md-8">
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
        </div>
    </body>
</html>

Sprint1/templates/crear_anuncio.html
{% load static %}
<html>
    <head>
        <title>Foro colunga</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">
		<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8" crossorigin="anonymous"></script>

    </head>
    <body>
        <div class="page-header">
            <a href="{% url 'editar' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
        </div>
        <div class="content container">
            <div class="row">
                <div class="col-md-8">
                          <h2>Nuevo Anuncio</h2>
    <form method="POST" class="post-form" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="file" name="poto" accept="image/*" id="id_photo" >

        <button type="submit" class="btn btn-primary">Crear Anuncio</button>
        <a href="{% url 'anuncios' %}"></a>
    </form>


                </div>
            </div>
        </div>
    </body>
</html>

Sprint1/templates/crear_usuario.html
<!DOCTYPE HTML>
<!--
	info plantilla:
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->

{% load static %}


<html>
	<head>
		<title>El wiwi</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">
		<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8" crossorigin="anonymous"></script>
        <script src="https://kit.fontawesome.com/626dd6f811.js" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="{% static 'css/main3.css' %}" />
		<noscript><link rel="stylesheet" href="{% static 'css/noscript2.css' %}" /></noscript>

	</head>
	<body class="is-preload">

		<!-- Wrapper -->
			<div id="wrapper">

				<!-- Header -->
					<header id="header" class="alt">

                            <span class="logo"><img src="{% static 'css/user1.png' %}" alt="" /></span>

						<p>BIENVENID@</p>

					</header>
				<!-- Nav -->
					<nav id="nav" class="">
						<ul>

						</ul>
					</nav>

				<!-- Main -->
					<div id="main">

						<!-- Teams -->
					<section id="anuncios" class="main special">
								<div class="spotlight">
									<div class="content">
										<header class="major">
											<h2>Nuevo Usuario</h2>
										</header>

                                 <form method="POST" class="post-form" enctype="multipart/form-data">{% csrf_token %}
                                    {{ form}}
                                     <br>
                                    <button type="submit" class="btn btn-primary">Crear Usuario</button>
                                <a href="{% url 'nusuario' %}"></a>
                            </form>


                                    </div>
                                </div>

                            </section>
					</div>
            </div>

		<!-- Scripts -->
			<script src="{% static 'js/jquery.min2.js' %}"></script>
			<script src="{% static 'js/jquery.scrollex.min2.js' %}"></script>
			<script src=  "{% static 'js/jquery.scrolly.min2.js' %}"></script>
			<script src="{% static 'js/browser.min.js2' %}"></script>
			<script src= "{% static 'js/breakpoints.min2.js' %}"></script>
			<script src="{% static 'js/util2.js' %}"></script>
			<script src="{% static 'js/main2.js' %}"></script>


	</body>
</html>

Sprint1/templates/crearforo.html
{% extends 'base.html' %}
{% block content %}
    <h2>nuevo post</h2>
    <form method="POST" class="post-form">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Guardar</button>
    </form>
{% endblock %}